// <auto-generated />
using System;
using MangaUpdater.Services.Database.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MangaUpdater.Services.Database.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MangaId")
                        .HasColumnType("integer");

                    b.Property<int>("NumberMajor")
                        .HasColumnType("integer");

                    b.Property<int>("NumberMinor")
                        .HasColumnType("integer");

                    b.Property<string>("NumberSuffix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("OriginalNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("MangaId", "SourceId", "OriginalNumber")
                        .IsUnique();

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.LogEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LogEvents");
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.Manga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AniListId")
                        .HasColumnType("integer");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MyAnimeListId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("TitleEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TitleRomaji")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AniListId")
                        .IsUnique();

                    b.HasIndex("MyAnimeListId")
                        .IsUnique();

                    b.ToTable("Mangas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AniListId = 109957,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx109957-EgJWdR7l9TBG.jpg",
                            MyAnimeListId = 147324,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "Second Life Ranker",
                            TitleRomaji = "Dubeon Saneun Ranker"
                        },
                        new
                        {
                            Id = 2,
                            AniListId = 121753,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx121753-vhvIdfxdaEdF.jpg",
                            MyAnimeListId = 127781,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "As a Reincarnated Aristocrat, I’ll Use My Appraisal Skill to Rise in the World",
                            TitleRomaji = "Tensei Kizoku, Kantei Skill de Nariagaru: Jakushou Ryouchi wo Uketsuida node, Yuushuu na Jinzai wo Fuyashiteitara, Saikyou Ryouchi ni Natteta"
                        },
                        new
                        {
                            Id = 3,
                            AniListId = 114048,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx114048-4HEtdYDcXI8r.jpg",
                            MyAnimeListId = 123456,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "The Ossan Newbie Adventurer, Trained to Death by the Most Powerful Party, Became Invincible",
                            TitleRomaji = "Shinmai Ossan Bouken-sha, Saikyou Party ni Shinu Hodo Kitaerarete Muteki ni Naru."
                        },
                        new
                        {
                            Id = 4,
                            AniListId = 101715,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/nx101715-4yYFDOadUtnC.jpg",
                            MyAnimeListId = 111466,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "Saving 80,000 Gold in Another World for my Retirement",
                            TitleRomaji = "Rougo ni Sonaete Isekai de 8-manmai no Kinka wo Tamemasu"
                        },
                        new
                        {
                            Id = 5,
                            AniListId = 163824,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx163824-KiablxybJD6i.jpg",
                            MyAnimeListId = 157888,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "Revenge of the Baskerville Bloodhound",
                            TitleRomaji = "Cheolhyeolgeomga Sanyanggaeui Hoegwi"
                        },
                        new
                        {
                            Id = 6,
                            AniListId = 149332,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx149332-adkSyOFY3c5U.jpg",
                            MyAnimeListId = 146949,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "The Swordmaster's Son",
                            TitleRomaji = "Geomsul Myeongga Mangnaeadeul"
                        },
                        new
                        {
                            Id = 7,
                            AniListId = 153883,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx153883-thHiGEnqxFoB.jpg",
                            MyAnimeListId = 151483,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "The SSS-Ranker Returns",
                            TitleRomaji = "SSS-geup Ranker Hoegwihada"
                        },
                        new
                        {
                            Id = 8,
                            AniListId = 125636,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx125636-g0gkyLZbo3Tz.png",
                            MyAnimeListId = 147322,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "The Max Level Hero Strikes Back!",
                            TitleRomaji = "Man-Level Yeongung-nim-kkeseo Gwihwan Hasinda!"
                        },
                        new
                        {
                            Id = 9,
                            AniListId = 151025,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx151025-j7nZBNb46cv9.jpg",
                            MyAnimeListId = 150561,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "Mythic Item Obtained",
                            TitleRomaji = "Sinhwa-geup Gwisok Item-eul Son-e Neoeotda"
                        },
                        new
                        {
                            Id = 10,
                            AniListId = 159441,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx159441-n919hUzb0j44.jpg",
                            MyAnimeListId = 154587,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "Pick Me Up",
                            TitleRomaji = "Pick Me Up!, Infinite Gacha"
                        },
                        new
                        {
                            Id = 11,
                            AniListId = 167318,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx167318-fmcRXTsFE99i.jpg",
                            MyAnimeListId = 159916,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "The Extra Is Too Powerful",
                            TitleRomaji = "Extra-ga Neomu Gangham"
                        },
                        new
                        {
                            Id = 12,
                            AniListId = 166635,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx166635-6Y7R6AZe52Fv.jpg",
                            MyAnimeListId = 160118,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "All-Master Necromancer",
                            TitleRomaji = "Absolute Necromancer"
                        },
                        new
                        {
                            Id = 13,
                            AniListId = 130511,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx130511-4O6dF8oaiVJh.jpg",
                            MyAnimeListId = 147995,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "The Player Who Can't Level Up",
                            TitleRomaji = "Level Up Mothaneun Player"
                        },
                        new
                        {
                            Id = 14,
                            AniListId = 137280,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx137280-C8kbBitLxlwR.png",
                            MyAnimeListId = 147392,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "I'm the Max-Level Newbie",
                            TitleRomaji = "Na Honja Man-Level Newbie"
                        },
                        new
                        {
                            Id = 15,
                            AniListId = 110989,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx110989-DKLKwQ5ojqXD.jpg",
                            MyAnimeListId = 122650,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "Failure Frame: I Became the Strongest and Annihilated Everything With Low-Level Spells",
                            TitleRomaji = "Hazurewaku no \"Joutai Ijou Skill\" de Saikyou ni Natta Ore ga Subete wo Juurin suru made"
                        },
                        new
                        {
                            Id = 16,
                            AniListId = 86635,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx86635-EdaLQmsn86Fy.png",
                            MyAnimeListId = 90125,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "Kaguya-sama: Love Is War",
                            TitleRomaji = "Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen"
                        },
                        new
                        {
                            Id = 17,
                            AniListId = 151457,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx151457-7v5jKk5yAnAc.png",
                            MyAnimeListId = 148458,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "The Overpowered Newbie",
                            TitleRomaji = "Newbie-ga Neomu Gangham"
                        },
                        new
                        {
                            Id = 18,
                            AniListId = 122063,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx122063-zq7rF3cdgxpX.jpg",
                            MyAnimeListId = 130331,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "Shangri-La Frontier",
                            TitleRomaji = "Shangri-La Frontier: Kusoge Hunter, Kamige ni Idoman to su"
                        },
                        new
                        {
                            Id = 19,
                            AniListId = 30013,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx30013-ulXvn0lzWvsz.jpg",
                            MyAnimeListId = 13,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "One Piece",
                            TitleRomaji = "One Piece"
                        },
                        new
                        {
                            Id = 20,
                            AniListId = 139572,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx139572-e3vwLcOVQISn.jpg",
                            MyAnimeListId = 147450,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "The Lone Necromancer",
                            TitleRomaji = "Na Honja Necromancer"
                        },
                        new
                        {
                            Id = 21,
                            AniListId = 100693,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/nx100693-SwgtbDgQosE7.jpg",
                            MyAnimeListId = 111225,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "The Unwanted Undead Adventurer",
                            TitleRomaji = "Nozomanu Fushi no Boukensha"
                        },
                        new
                        {
                            Id = 22,
                            AniListId = 153284,
                            CoverUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx153284-roAlRmlRM7Vs.png",
                            MyAnimeListId = 150210,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TitleEnglish = "After Ten Millennia in Hell",
                            TitleRomaji = "Man Nyeon Man-e Gwihwanhan Player"
                        });
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.MangaSource", b =>
                {
                    b.Property<int>("MangaId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MangaId", "SourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("MangaSources");

                    b.HasData(
                        new
                        {
                            MangaId = 2,
                            SourceId = 1,
                            Id = 2,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "fef2e4da-36f9-48e9-8317-2516f4b6ab14"
                        },
                        new
                        {
                            MangaId = 3,
                            SourceId = 1,
                            Id = 3,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "a2320293-f00e-43a0-8d08-1110cf26a894"
                        },
                        new
                        {
                            MangaId = 4,
                            SourceId = 1,
                            Id = 4,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "89ed3ec2-ebe6-4d6b-92eb-d753a8bb365e"
                        },
                        new
                        {
                            MangaId = 5,
                            SourceId = 2,
                            Id = 5,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "/comics/revenge-of-the-iron-blooded-sword-hound-5abb513e"
                        },
                        new
                        {
                            MangaId = 6,
                            SourceId = 2,
                            Id = 6,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "/comics/swordmasters-youngest-son-5abb513e"
                        },
                        new
                        {
                            MangaId = 7,
                            SourceId = 2,
                            Id = 7,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "/comics/return-of-the-sss-class-ranker-5abb513e"
                        },
                        new
                        {
                            MangaId = 8,
                            SourceId = 2,
                            Id = 8,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "/comics/the-max-level-hero-has-returned-5abb513e"
                        },
                        new
                        {
                            MangaId = 9,
                            SourceId = 2,
                            Id = 9,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "/comics/i-obtained-a-mythic-item-5abb513e"
                        },
                        new
                        {
                            MangaId = 10,
                            SourceId = 2,
                            Id = 10,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "/comics/pick-me-up-infinite-gacha-5abb513e"
                        },
                        new
                        {
                            MangaId = 12,
                            SourceId = 2,
                            Id = 12,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "/comics/absolute-necromancer-5abb513e"
                        },
                        new
                        {
                            MangaId = 13,
                            SourceId = 2,
                            Id = 13,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "/comics/player-who-cant-level-up-5abb513e"
                        },
                        new
                        {
                            MangaId = 14,
                            SourceId = 2,
                            Id = 14,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "/comics/solo-max-level-newbie-5abb513e"
                        },
                        new
                        {
                            MangaId = 15,
                            SourceId = 1,
                            Id = 15,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "0b171f64-89a5-4c37-b5f9-75cca57e8787"
                        },
                        new
                        {
                            MangaId = 16,
                            SourceId = 1,
                            Id = 16,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "37f5cce0-8070-4ada-96e5-fa24b1bd4ff9"
                        },
                        new
                        {
                            MangaId = 17,
                            SourceId = 3,
                            Id = 17,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "214"
                        },
                        new
                        {
                            MangaId = 21,
                            SourceId = 1,
                            Id = 21,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "6e44705b-9f80-42f6-9ebb-1141fbe8320e"
                        });
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DefaultUserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("HtmlXPath");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("QueueName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("RateLimitMilliseconds")
                        .HasColumnType("integer");

                    b.Property<string>("RequestMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("HttpGet");

                    b.Property<bool>("RequiresBrowser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("SupportsPagination")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Sources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://api.mangadex.org/manga/",
                            DefaultUserAgent = "MangaUpdater/1.0",
                            EngineType = "JsonApi",
                            IsEnabled = true,
                            Name = "MangaDex",
                            QueueName = "get-chapters-Mangadex",
                            RequestMode = "HttpGet",
                            RequiresBrowser = false,
                            Slug = "mangadex",
                            SupportsPagination = true,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BaseUrl = "https://asurascans.com",
                            EngineType = "HtmlXPath",
                            IsEnabled = true,
                            Name = "AsuraScans",
                            QueueName = "get-chapters-AsuraScans",
                            RequestMode = "HttpGet",
                            RequiresBrowser = false,
                            Slug = "asurascans",
                            SupportsPagination = false,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BaseUrl = "https://vortexscans.org/api/chapters?postId=",
                            EngineType = "JsonApi",
                            IsEnabled = true,
                            Name = "VortexScans",
                            QueueName = "get-chapters-VortexScans",
                            RequestMode = "HttpGet",
                            RequiresBrowser = false,
                            Slug = "vortexscans",
                            SupportsPagination = true,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.SourceApiProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChapterDatePath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ChapterNumberPath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ChapterUrlPath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DataRootPath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EndpointTemplate")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("GET");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LimitParameterName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NextPagePath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OffsetParameterName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaginationMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ResultLimit")
                        .HasColumnType("integer");

                    b.Property<string>("ResultUrlTemplate")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "Version")
                        .IsUnique();

                    b.ToTable("SourceApiProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChapterDatePath = "attributes.createdAt",
                            ChapterNumberPath = "attributes.chapter",
                            ChapterUrlPath = "id",
                            DataRootPath = "data",
                            EndpointTemplate = "{BaseUrl}{MangaUrlPart}/feed?translatedLanguage[]=en&limit=199&order[chapter]=asc&limit=200&offset={Offset}",
                            HttpMethod = "GET",
                            IsActive = true,
                            OffsetParameterName = "offset",
                            PaginationMode = "Offset",
                            ResultLimit = 200,
                            ResultUrlTemplate = "https://mangadex.org/chapter/{Value}",
                            SourceId = 1,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            ChapterDatePath = "createdAt",
                            ChapterNumberPath = "number",
                            DataRootPath = "post.chapters",
                            EndpointTemplate = "{BaseUrl}{MangaUrlPart}&skip={Offset}&take=200&order=desc",
                            HttpMethod = "GET",
                            IsActive = true,
                            LimitParameterName = "take",
                            OffsetParameterName = "skip",
                            PaginationMode = "Offset",
                            ResultLimit = 200,
                            SourceId = 3,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        });
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.SourceRequestProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcceptLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("GET");

                    b.Property<string>("Referrer")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("UrlTemplate")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("UseCookies")
                        .HasColumnType("boolean");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "Version")
                        .IsUnique();

                    b.ToTable("SourceRequestProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptLanguage = "en-US",
                            HeadersJson = "{\"User-Agent\":\"MangaUpdater/1.0\"}",
                            IsActive = true,
                            Method = "GET",
                            SourceId = 1,
                            TimeoutSeconds = 30,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlTemplate = "{BaseUrl}{MangaUrlPart}/feed?translatedLanguage[]=en&limit=199&order[chapter]=asc&limit=200&offset={Offset}",
                            UseCookies = false,
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Method = "GET",
                            SourceId = 2,
                            TimeoutSeconds = 30,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlTemplate = "{BaseUrl}{MangaUrlPart}",
                            UseCookies = false,
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Method = "GET",
                            SourceId = 3,
                            TimeoutSeconds = 30,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlTemplate = "{BaseUrl}{MangaUrlPart}&skip={Offset}&take=200&order=desc",
                            UseCookies = false,
                            Version = 1
                        });
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.SourceScrapingProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChapterDateAttribute")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChapterDateRegex")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ChapterDateXPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ChapterNodesXPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ChapterNumberAttribute")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChapterNumberRegex")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ChapterNumberXPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ChapterSortMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ChapterUrlAttribute")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChapterUrlXPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DateCulture")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DateFormatPrimary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DateFormatSecondary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DateParseMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeduplicationKeyMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IgnoreTextContains1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IgnoreTextContains2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IgnoreTextContains3")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PaginationNextPageXPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PaginationUrlTemplate")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RelativeDateRegex")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("ResultLimit")
                        .HasColumnType("integer");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("UrlJoinMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UrlPrefix")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "Version")
                        .IsUnique();

                    b.ToTable("SourceScrapingProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChapterDateRegex = "((?:(?:\\d+|a|an|one)\\s+(?:second|sec|minute|min|hour|hr|day|week|wk|month|mo|year|yr)(?:s)?\\s+ago)|today|yesterday|last\\s+(?:week|month|year)|(?:[A-Za-z]{3}\\s+\\d{1,2},\\s+\\d{4}))",
                            ChapterDateXPath = ".",
                            ChapterNodesXPath = "//a[contains(@href, '/chapter/')]",
                            ChapterNumberAttribute = "href",
                            ChapterNumberRegex = "chapter/(\\d+(\\.\\d+)?)",
                            ChapterSortMode = "NumericAscending",
                            ChapterUrlAttribute = "href",
                            ChapterUrlXPath = ".",
                            DateCulture = "en-US",
                            DateFormatPrimary = "MMM dd, yyyy",
                            DateParseMode = "RelativeOrFormat",
                            DeduplicationKeyMode = "ChapterNumber",
                            IgnoreTextContains1 = "First Chapter",
                            IgnoreTextContains2 = "Latest Chapter",
                            IsActive = true,
                            RelativeDateRegex = "((?:\\d+|a|an|one))\\s+(second|sec|minute|min|hour|hr|day|week|wk|month|mo|year|yr)s?\\s+ago",
                            ResultLimit = 500,
                            SourceId = 2,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlJoinMode = "BaseUrlPrefix",
                            Version = 1
                        });
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("user");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.Chapter", b =>
                {
                    b.HasOne("MangaUpdater.Services.Database.Entities.Manga", "Manga")
                        .WithMany("Chapters")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaUpdater.Services.Database.Entities.Source", "Source")
                        .WithMany("Chapters")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.MangaSource", b =>
                {
                    b.HasOne("MangaUpdater.Services.Database.Entities.Manga", "Manga")
                        .WithMany("MangaSources")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaUpdater.Services.Database.Entities.Source", "Source")
                        .WithMany("MangaSources")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.SourceApiProfile", b =>
                {
                    b.HasOne("MangaUpdater.Services.Database.Entities.Source", "Source")
                        .WithMany("ApiProfiles")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.SourceRequestProfile", b =>
                {
                    b.HasOne("MangaUpdater.Services.Database.Entities.Source", "Source")
                        .WithMany("RequestProfiles")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.SourceScrapingProfile", b =>
                {
                    b.HasOne("MangaUpdater.Services.Database.Entities.Source", "Source")
                        .WithMany("ScrapingProfiles")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.Manga", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("MangaSources");
                });

            modelBuilder.Entity("MangaUpdater.Services.Database.Entities.Source", b =>
                {
                    b.Navigation("ApiProfiles");

                    b.Navigation("Chapters");

                    b.Navigation("MangaSources");

                    b.Navigation("RequestProfiles");

                    b.Navigation("ScrapingProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
